config/routes.rb
Rails.application.routes.draw do
  get "home/profile"
  get "bookings/my_bookings"
  resources :djs do
    resources :bookings
    resources :reviews
    resources :songs
  end
  resources :hosts
  resources :charges, only: [:new, :create]
  root 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/host.rb
class Host < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true
  validates :image, presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]
  before_action :check_dj_presence, only: [:new, :create]
  before_action :check_host_presence, only: [:new, :create]
  before_action :only_edit_own_host_page, only: [:edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)
    @host.user_id = current_user.id

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to hosts_path, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    def check_dj_presence
      if current_user.dj
        flash[:notice] = "DJ profile found, user is not able to create host profile."
        redirect_to root_path
      end
    end

    def check_host_presence
      if current_user.host
        flash[:notice] = "You already have a Host profile!"
        redirect_to root_path
      end
    end

    def only_edit_own_host_page
      if @host.user_id != current_user.id
        flash[:notice] = "You are only allowed to make changes to your own profile"
        redirect_to hosts_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:name, :location, :image, :user_id)
    end
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= simple_form_for(@host) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :location, placeholder: 'eg. Sydney, Australia' %>
    <%= f.input :image, as: :file %>
    <!-- <%= f.association :user %> -->
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host %>

<br>
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<% @hosts.each do |host| %>
  <% if host.user == current_user %>
    <div class="container">
      <div id="host-card-body" class="card mx-auto">
        <h1 id="host-card-header" class="card-header"><%= host.name %></h1>
        <br>
        <%=  image_tag(host.image_url, class:"card-img-top mx-auto") %>
        <div id="host-card-text" class="card-text">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Email: <%= host.user.email %></li>
            <li class="list-group-item">Location: <%= host.location %></li>
            <li class="list-group-item"><%= link_to 'Edit', edit_host_path(host) %></li>
            <li class="list-group-item"><%= link_to 'Back', root_path %></li>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
  <% end %>
<% end %>

<!-- <% @hosts.each_slice(3) do |hosts| %>
  <div class="row">
    <% hosts.each do |host| %>
      <div class="col-md-4">
        <div class="item">
          <div class="card">
          <h3 class="card-header text-center"><%= host.name %></h3>
          <br>
            <div class="card-img">
              <%= link_to image_tag(host.image_url, class:"card-img-top"),host_path(host) %>
            </div>
            <div class="card-body">
            </div>
            <ul class="list-group list-group-flush text-center">
              <% if host.user == current_user %>
                <%= link_to 'Edit', edit_host_path(host), class:"list-group-item" %>
                <%= link_to 'Back', root_path, class:"list-group-item" %>
              <% else %>
                <%= link_to 'Back', root_path, class:"list-group-item" %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %> -->

app/views/hosts/new.html.erb
<div class="card mx-auto" style="width: 30rem;">
  <div class="card-body">
    <h1>New Host</h1>
    <%= render 'form', host: @host %>
    <!-- <%= link_to 'Back', hosts_path %> -->
    <br>
    <%= link_to 'Back', home_profile_path, class:"btn btn-primary" %>
  </div>
</div>
<br>
<br>

app/views/hosts/show.html.erb
<div class="container">
  <div class="card mx-auto text-center">
    <div class="card-body mx-auto">
      <h1 class="card-header"><%= @host.name %></h1>
      <br>
      <%=  image_tag(@host.image_url, class:"card-img-top mx-auto") %>
      <div class="card-text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Email: <%= @host.user.email %></li>
          <li class="list-group-item">Location: <%= @host.location %></li>
          <li class="list-group-item"><%= link_to 'Back', hosts_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>