config/routes.rb
Rails.application.routes.draw do
  get "home/profile"
  get "bookings/my_bookings"
  resources :djs do
    resources :bookings
    resources :reviews
    resources :songs
  end
  resources :hosts
  resources :charges, only: [:new, :create]
  root 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dj.rb
class Dj < ApplicationRecord
  include PgSearch
  multisearchable :against => [:name, :rate, :location ]

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :rate, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 80}, presence: true
  validates :image, presence: true
  # validates :audio, presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :bookings, dependent: :destroy
  # has_many :reviews, through: :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :songs, dependent: :destroy



  scope :sorted, ->{ order(name: :asc) }

  pg_search_scope :search,
                  against: [
                    :name,
                    :rate,
                    :location,
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }

  def self.perform_search(keyword)
    if keyword.present?
    then Dj.search(keyword)
  else Dj.all
    end.sorted
  end

end

app/controllers/djs_controller.rb
class DjsController < ApplicationController
  before_action :set_dj, only: [:show, :edit, :update, :destroy]
  before_action :check_dj_presence, only: [:new, :create]
  before_action :check_host_presence, only: [:new, :create]
  before_action :only_edit_own_dj_page, only: [:edit, :update, :destroy]
  # GET /djs
  # GET /djs.json
  def index
    # @djs = Dj.all
    if params[:search].present?
      @djs = Dj.perform_search(params[:search])
    else
      @djs = Dj.all
    end
  end

  # GET /djs/1
  # GET /djs/1.json
  def show
  end

  # GET /djs/new
  def new
    @dj = Dj.new
  end

  # GET /djs/1/edit
  def edit
  end

  # POST /djs
  # POST /djs.json
  def create
    @dj = Dj.new(dj_params)
    @dj.user_id = current_user.id

    respond_to do |format|
      if @dj.save
        format.html { redirect_to @dj, notice: 'Dj was successfully created.' }
        format.json { render :show, status: :created, location: @dj }
      else
        format.html { render :new }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /djs/1
  # PATCH/PUT /djs/1.json
  def update
    respond_to do |format|
      if @dj.update(dj_params)
        format.html { redirect_to @dj, notice: 'Dj was successfully updated.' }
        format.json { render :show, status: :ok, location: @dj }
      else
        format.html { render :edit }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /djs/1
  # DELETE /djs/1.json
  def destroy
    @dj.destroy
    respond_to do |format|
      format.html { redirect_to djs_url, notice: 'Dj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dj
      @dj = Dj.find(params[:id])
    end

    def check_dj_presence
      if current_user.dj
        flash[:notice] = "You already have a DJ profile!"
        redirect_to root_path
      end
    end

    def check_host_presence
      if current_user.host
        flash[:notice] = "Host profile found, user is not able to create dj profile."
        redirect_to root_path
      end
    end

    def only_edit_own_dj_page
      if @dj.user_id != current_user.id
        flash[:notice] = "Sorry, but you are only allowed to make changes to your own profile"
        redirect_to djs_path
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def dj_params
      params.require(:dj).permit(:name, :description, :location, :rate, :image, :user_id)
    end
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/views/djs/_form.html.erb
<%= simple_form_for(@dj) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name, placeholder: 'Your DJ name or actual name' %>
    <%= f.input :description, placeholder: 'eg. Past experiences, music genre, etc' %>
    <%= f.input :location, placeholder: 'eg. Sydney, Australia' %>
    <%= f.input :rate, placeholder: 'Amount you charge per hour' %>
    <%= f.input :image, as: :file %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/djs/edit.html.erb
<h1>Editing Dj</h1>

<%= render 'form', dj: @dj %>

<%= link_to 'Show', @dj %> |
<%= link_to 'Back', djs_path %>

app/views/djs/index.html.erb
<% @djs.each_slice(3) do |djs| %>
  <div class="row">
    <% djs.each do |dj| %>
      <div class="col-md-4">
        <div class="item">
          <div class="card">
          <h3 id="dj-card-header" class="card-header"><%= dj.name %></h3>
          <br>
            <div class="card-img">
              <%= link_to image_tag(dj.image_url, class:"card-img-top"),dj_path(dj) %>
            </div>
            <div class="card-body">
            </div>
            <ul class="list-group list-group-flush text-center">
              <% if dj.user == current_user %>
                <%= link_to 'My Uploads',  dj_songs_path(dj), class:"list-group-item" %>
                <%= link_to 'Upload',  new_dj_song_path(dj), class:"list-group-item" %>
                <%= link_to 'Bookings',  dj_bookings_path(dj),  class:"list-group-item" %>
                <%= link_to 'Reviews', dj_reviews_path(dj), class:"list-group-item" %>
                <%= link_to 'Edit', edit_dj_path(dj), class:"list-group-item"  %>
                <%= link_to 'Destroy', dj, method: :delete, data: { confirm: 'Are you sure?' }, class:"list-group-item" %>
              <% else %>
                <%= link_to 'Uploads',  dj_songs_path(dj), class:"list-group-item" %>
                <%= link_to 'Book',  new_dj_booking_path(dj),class:"list-group-item" %>
                <%= link_to 'Reviews', dj_reviews_path(dj), class:"list-group-item" %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/djs/new.html.erb
<div class="card mx-auto" style="width: 30rem;">
  <div class="card-body">
    <h1>New Dj</h1>
    <%= render 'form', dj: @dj %>
    <!-- <%= link_to 'Back', djs_path, class:"btn btn-primary" %> -->
    <br>
    <%= link_to 'Back', home_profile_path, class:"btn btn-primary" %>
  </div>
</div>
<br>
<br>

app/views/djs/show.html.erb
<div class="col-md-6 mx-auto">
  <div id="dj-card-body" class="card-body">
    <h1 id="dj-card-header" class="card-header"><%= @dj.name %></h1>
    <br>
    <%=  image_tag(@dj.image_url, class:"card-img-top") %>
    <div id="dj-card-text" class="card-text">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Description: <%= @dj.description %></li>
        <li class="list-group-item">Email: <%= @dj.user.email %></li>
        <li class="list-group-item">Location: <%= @dj.location %></li>
        <li class="list-group-item">Rate: $<%= @dj.rate %>/hour</li>
        <li class="list-group-item"><%= link_to 'Back', djs_path %></li>
      </ul>
    </div>
  </div>
</div>