config/routes.rb
Rails.application.routes.draw do
  get "home/profile"
  get "bookings/my_bookings"
  resources :djs do
    resources :bookings
    resources :reviews
    resources :songs
  end
  resources :hosts
  resources :charges, only: [:new, :create]
  root 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :dj
  mount_uploader :image, ImageUploader
  mount_uploader :audio, AudioUploader
  validates :title, presence: true
  validates :genre, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :audio, presence: true
  GENRE = %w{ None Ambient Dance-&-EDM Deep-House Dubstep Electronic Hip-Hop-&-Rap House Techno Trance Other}
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :set_dj, only: [:new, :create, :edit, :show, :update, :destroy, :index]

  # GET /songs
  # GET /songs.json
  def index
    # @songs = Song.all
    @songs = Song.where("dj_id=?", params[:dj_id])
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @song.dj_id = @dj.id

    respond_to do |format|
      if @song.save
        format.html { redirect_to dj_song_path(@dj, @song), notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to dj_song_path(@dj, @song), notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to dj_songs_path, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    def set_dj
      @dj = Dj.find(params[:dj_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :genre, :description, :image, :audio, :dj_id)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for([@dj,@song]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, placeholder: 'Name your track' %>
    <%= f.input :genre, collection: Song::GENRE, prompt: "Select Genre" %>
    <%= f.input :description, placeholder: 'Describe your track' %>
    <%= f.input :image, as: :file %>
    <%= f.input :audio, as: :file %>
    <!-- <%= f.association :dj %> -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', dj_song_path %> |
<%= link_to 'Back', dj_songs_path %>

app/views/songs/index.html.erb
<% @songs.each_slice(3) do |songs| %>
  <div class="row">
    <% songs.each do |song| %>
      <div class="col-md-4">
        <div class="item">
          <div class="card">
          <h3 class="card-header"><%= song.title %></h3>
          <br>
            <div class="card-img">
              <%= link_to image_tag(song.image_url, class:"card-img-top"),dj_song_path(@dj,song) %>
            </div>
            <div class="card-body">
            </div>
            <ul class="list-group list-group-flush text-center">
              <% if @dj.user == current_user %>
                <%= link_to 'Edit', edit_dj_song_path(@dj,song), class:"list-group-item" %>
                <%= link_to 'Back', djs_path(@dj,song), class:"list-group-item" %>
                <%= link_to 'Destroy', dj_song_path(@dj,song), method: :delete, data: { confirm: 'Are you sure?' }, class:"list-group-item" %>
              <% else %>
              <%= link_to 'Back', djs_path(@dj,song), class:"list-group-item" %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<!-- <h1>Songs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Image</th>
      <th>Audio</th> -->
      <!-- <th colspan="3"></th>
    </tr>
  </thead> -->

  <!-- <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.genre %></td>
        <td><%= song.description %></td> -->
        <!-- <td><%= song.image %></td>
        <td><%= song.audio %></td> -->
        <!-- <td><%= link_to 'Show', dj_song_path(@dj,song) %></td>
        <td><%= link_to 'Edit', edit_dj_song_path(@dj,song) %></td>
        <td><%= link_to 'Destroy', dj_song_path(@dj,song), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<!-- <br> -->

<!-- <%= link_to 'New Song', new_dj_song_path %> -->

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', dj_songs_path %>

app/views/songs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div id="dj-card-body" class="card-body">
        <h1 id="dj-card-header" class="card-header"><%= @dj.name %></h1>
        <%=  image_tag(@song.image_url, class:"card-img-top") %>
        <div id="dj-card-text" class="card-text">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Title: <%= @song.title %></li>
            <li class="list-group-item">Genre: <%= @song.genre %></li>
            <li class="list-group-item">Description: <%= @song.description %></li>
          <li class="list-group-item"><%= audio_tag @song.audio_url,:autoplay=>false,:controls => true unless @song.audio.blank? %></li>
          <% if @dj.user == current_user %>
            <li class="list-group-item"><%= link_to 'Edit', edit_dj_song_path(@dj) %></li>
            <li class="list-group-item"><%= link_to 'Back', dj_songs_path(@dj) %></li>
          <% else %>
            <li class="list-group-item"><%= link_to 'Back', dj_songs_path(@dj) %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>