config/routes.rb
Rails.application.routes.draw do
  get "home/profile"
  get "bookings/my_bookings"
  resources :djs do
    resources :bookings
    resources :reviews
    resources :songs
  end
  resources :hosts
  resources :charges, only: [:new, :create]
  root 'home#index'
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_dj, only: [:new, :create, :edit, :show, :update, :destroy, :index]
  before_action :check_dj_presence, only: [:new, :create, :edit, :update, :destroy]
  before_action :only_host_can_edit_review, only: [:edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    # @reviews = Review.all
    @reviews = Review.where("dj_id=?", params[:dj_id])
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    if Review.where("host_id = ? AND dj_id = ?", current_user.host.id, @dj.id).exists?
        redirect_to djs_path
        flash[:notice] = "You're only allowed to review once"
    else
        @review = Review.new
    end
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    # @review = Review.new
    # @review.host_id = current_user.host.id
    # @review.dj_id = @dj.id
    @review = Review.new(review_params)
    @review.host_id = current_user.host.id
    @review.dj_id = @dj.id


    respond_to do |format|
      if @review.save
        format.html { redirect_to  dj_reviews_path, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to dj_reviews_path, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to dj_reviews_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_dj
      @dj = Dj.find(params[:dj_id])
    end

    def check_dj_presence
      if current_user.dj
        flash[:notice] = "DJ user detected, only host can create/edit/delete reviews"
        redirect_to djs_path
      end
    end

    def only_host_can_edit_review
      if @review.host_id != current_user.host.id
        flash[:notice] = "You are only allowed to make changes to your own reviews"
        redirect_to dj_reviews_path(@dj)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@dj,@review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating, collection: Review::RATING, prompt: "Select Rating" %>
    <%= f.input :comment %>
    <!-- <%= f.association :host %>
    <%= f.association :dj %> -->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', dj_review_path(@dj) %> |
<%= link_to 'Back', dj_reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table class="table text-center">
  <thead>
    <tr>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= link_to 'Show', dj_review_path(@dj,review) %></td>
        <td><%= link_to 'Edit', edit_dj_review_path(@dj,review) %></td>
        <td><%= link_to 'Destroy', dj_review_path(@dj,review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_dj_review_path %>
<br><br>
<%= link_to 'Back', djs_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>
<%= link_to 'Cancel', djs_path, class:"btn btn-danger" %>

app/views/reviews/show.html.erb
<div class="card mx-auto" style="width: 25rem;">
  <div class="card-body">
    <ul class="list-group list-group-flush text-center">
      <h3 id="dj-card-header" class="card-header">Review</h3>
        <ul class="list-group-item">Rating: <%= @review.rating %></ul>
        <ul class="list-group-item">Reviewed by: <%= @review.host.name %></ul>
        <ul class="list-group-item">Comment: <%= @review.comment %></ul>
        <ul class="list-group-item">Review for: <%= @review.dj.name %></ul>
      <%= link_to 'Back', dj_reviews_path,class:"list-group-item" %>
    </ul>
  </div>
</div>